export enum CuisineType {
  All = "",
  American = "American",
  Asian = "Asian",
  British = "British",
  Caribbean = "Caribbean",
  Central_Europe = "Central Europe",
  Chinese = "Chinese",
  Eastern_Europe = "Eastern Europe",
  French = "French",
  Indian = "Indian",
  Italian = "Italian",
  Japanese = "Japanese",
  Kosher = "Kosher",
  Mediterranean = "Mediterranean",
  Mexican = "Mexican",
  Middle_Eastern = "Middle Eastern",
  Nordic = "Nordic",
  South_American = "South American",
  South_Easr_Asian = "South East Asian"
}
